- 1.1.16
- _NAME: G102 Prodigy Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, reprogrammable-keys, persistent-remappable-keys,
    divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _modelId: C08400000000
  _sensitive: {dpi: true, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore, led_control: true, led_zone_2: false,
    onboard_profiles: true, report_rate: false}
  _unitId: '32384713'
  dpi: 1300
  led_control: 0
  led_zone_2: !LEDEffectSetting {ID: 10, color: 16416882, intensity: 0, period: 2550, ramp: 0, speed: 0}
  onboard_profiles: 1
  report_rate: 1
